### ISSUE TITLE
Issues in the Design Draft

### ISSUE THREAD

**Issue by gerane** [PowerShellOrg/Plaster#12]
I know these are just an example, but it was a bit confusing to me when trying to create a custom manifest. I think you have a typo here in the 'CreateRootFolder', but also these are missing the required='true'

``` xml
<parameters>
        <parameter name='ModuleName' required='true' prompt='Enter the name of the module'/>
        <parameter name='Version' default='1.0.0' store='true' prompt='Enter the version number for the module'/>
        <parameter name='CreateRootFoler' default='Yes' prompt='Do you want to create the root folder for the project'/>
</parameters>
```

Also, I am looking through the invokeplaster.ps1 and I am guessing the CreateRootFolder is no longer a valid parameter? What I would like to be able to do, is provide a Destination Path, and then it create a new Directory in the Destination Path with my ModuleName or other Template variable. Is this currently possible?

**Comment by rkeithhill** [comment]
That is a bad example for `choice` input.  The better example is in `Examples\NewModuleTemplate\plasterManifest.xml`.  

WRT to destination path, Invoke-Plaster will create the destination path if it doesn't exist.  Ditto for file destination - if the parent folder(s) don't exist "within" the destination dir, they will be created.

What we are currently missing is a way to create an `empty` folder.  Not that Git would allow you to commit that. #THINGSIDONTLIKEABOUTGIT  :-)

**Comment by gerane** [comment]
I was able to create empty folders like this

``` xml
<file source='Toolkit\Files\'
        destination='Toolkit\Files\'/>
<file source='Toolkit\SupportFiles\'
        destination='Toolkit\SupportFiles\'/>
```

**Comment by rkeithhill** [comment]
That's wasn't the intended usage but hey, if it works...  :-)

**Comment by gerane** [comment]
lol

**Comment by gerane** [comment]
I take it back, it looks like it is not making the empty directories now. Is this eventually planned?

**Comment by rkeithhill** [comment]
I updated the example in the `DesignNotes.md` document to reflect the current state of `choice` and `multichoice` functionality.  

As for creating an empty directory, yes, I would like to support that.  It should be easy enough to add.  Just wondering though if a `<directory destination="Toolkit\SupportFiles"/>` would leave people they **have** to do that for every subdir when `<file .../>` will create subdirs as long as their is a file go into them.  

I wonder if it would be too weird if we supported this syntax:
```xml
<file source='' destination='Toolkit\Files\'/>
```

Oh wait a tic. That works. Is that sufficient long term?

**Comment by gerane** [comment]
I have been thinking this one over. I think this works as a short term solution if documented, but long term I feel this might be confusing. It would be ideal if someone can just quickly look at a manifest and understand how it works, and adding quirks like that kind of go against the way you would think directories should work.

I feel Plaster should try to stay as inviting and user friendly as possible. I am going to guess that a very large number of users who start using this have never used a generator like this before.
