### ISSUE TITLE
Looking for guidance

### ISSUE THREAD

**Issue by dfinke** [PowerShellOrg/Plaster#15]
I'm setting up a new module to publish to the gallery.

I've got a process that works. Probably can be improved and I figured maybe a good fit for plaster.

I usually start with a ps1 to try out an idea. Once it is reasonably stable, I move to make it a module, prep it to be published and versioned in a public git repo. This means creating a properly named psd1, psm1 in a new git directory. I have an `InstallModule.ps1` and `PublishToGallery.ps1`. `InstallModule.ps1` simulates `Install-Module` so I can smoke test it before publishing. `PublishToGallery.ps1` does just that.

It be great if I could plaster this entire thing. Varying the name and scaffolding the rest.

Is this a fit for Plaster? Can it be easily templated today?

Thanks

**Comment by rkeithhill** [comment]
The current early preview can create files & folders based on input from the user.  It can modify files but there are some issues with the pattern regex processing I need to fix.   It currently does not do things like initializing a git repo.   

Take a look at the `Examples\NewModuleTemplate`, specifically the `plasterManifest.xml` file.   You should be able to scaffold your customized files easily enough.

**Comment by Jaykul** [comment]
Off topic, but what is up with the reaction "emoji" ....
![2016-05-22_23-58-21](https://cloud.githubusercontent.com/assets/192942/15460004/47e35e0e-2079-11e6-9580-24e072fbda27.png)

**Comment by Jaykul** [comment]
Hey you two ... I've been thinking about some "guidance" and "best practices" for Module development (specifically, using function-per-file for development, but deploying as one psm1) ... 

I wonder if this is the sort of thing we can use the "default" module template to teach people ...

I also wonder if there's a good place to have a conversation about how to do this with "the people who care" ...

**Comment by rkeithhill** [comment]
Sounds good to me. Probably best discussed on Best Practices GH project. We will encode the recommendations into the default Plaster templates.
