### ISSUE TITLE
How to modify contents of all files contained in a flat directory?

### ISSUE THREAD

**Issue by sundmoon** [PowerShellOrg/Plaster#250]
Assuming that directory has files from various sources that contents have to be modified identically

I am new to Plaster, need advice by experts and developers

I wrote a Plaster manifest to generate PS module build pipelines according to [PSHitchhiker](https://github.com/Xainey/PSHitchhiker) by Michael Willis 
https://github.com/sundmoon/NewPowershellManifestModule_PSHitchhiker

**Comment by rkeithhill** [comment]
If the files already exist (before the invocation of the template), then use the `<modify>` directive.  It is basically a regex search & replace mechanism.  You'll have to use one `<modify>` directive per file.  If the set of files isn't known ahead of time, then I don't think Plaster will work in its current form.

**Comment by sundmoon** [comment]
> If the set of files isn't known ahead of time, then I don't think Plaster will work in its current form.

Okay, I meant exactly this case
What'd you recommend according your vision?

I may write personal workarounds in hope of minor changes needed with future versions of Plaster, or I may use an external tool with Plaster.

**Comment by rkeithhill** [comment]
I think support for this scenario can be added based on the same wildcard spec we use for `<file>` copies.  That means if you don't want to use *.* which is likely, then you'd have a different `<modify>` element for each extension you plan to modify e.g. *.ps1, *.psm1, etc.

**Comment by sundmoon** [comment]
I'm dubious that what I have written is the most advanced usage of Plaster at the moment. May you provide links to complex projects utilizing it "in the right way"?

**Comment by rkeithhill** [comment]
We don't have many advanced templates yet.  You can take a look at https://github.com/PowerShell/Plaster/blob/master/examples/NewModule/plasterManifest.xml but it doesn't currently use `<modify>`.    Although, at one point it did use modify to modify a VSCode tasks.json file.

**Comment by LaurentDardenne** [comment]
An example:
```xml
      <!-- Personnal todo list -->
         <!-- create a file from a template -->
        <templateFile source='Templates\TodoList.T.tdl' 
            destination='${PLASTER_PARAM_ProjectName}.tdl' 
            encoding='UTF8'/>
        
         <!-- Exclude it inside .gitignore file -->   
        <file source='Templates\_gitignore'
              destination='.gitignore'/>
            <modify path='.gitIgnore' encoding='UTF8'>
              <replace>
                     <!-- Append  -->
                  <original>(?s)^(.*)$</original>
                  <substitute expand='true'>``$0${PLASTER_PARAM_ProjectName}.tdl</substitute>
              </replace>
            </modify> 
```

Create a new manifest and change the RequiredModules key ( If requested) :
```xml
        <newModuleManifest destination='${PLASTER_PARAM_ModuleName}.psd1'
            moduleVersion='$PLASTER_PARAM_Version'
            rootModule='${PLASTER_PARAM_ModuleName}.psm1'
            author='$PLASTER_PARAM_FullName'
            description='$PLASTER_PARAM_ModuleDesc'
            encoding='UTF8'/>
            
            <modify path='${PLASTER_PARAM_ModuleName}.psd1' encoding='UTF8' 
                    condition="$PLASTER_PARAM_Log4Net -eq 'True'">
                <replace>
                    <original>(?s)# RequiredModules = \@\(\)</original>
                    <substitute>RequiredModules=@{ModuleName="Log4Posh";GUID="f796dd07-541c-4ad8-bfac-a6f15c4b06a0"; ModuleVersion="1.1.0.0"}</substitute>
                </replace>
            </modify>
```
