### ISSUE TITLE
Avoid overwritting file in VS Code user snippet files.

### ISSUE THREAD

**Issue by larssb** [PowerShellOrg/Plaster#271]
I'm sitting on a case where I would like to copy a powershell.json VS Code file to the users VS Code snippets folder. But I risk overwritting a powershell.json file already there. As far as I can read in the VS Code documentation snippet files are global per user and not per workspace. Also I see no help here (https://code.visualstudio.com/docs/editor/userdefinedsnippets).
In the Plaster documentation https://github.com/PowerShell/Plaster/blob/master/docs/en-US/about_Plaster_CreatingAManifest.help.md#content-element-modify one can read about the modify element. But, as far as I can conclude that doesn't fit this scenario. Anyone with a good idea :-) ?
For good measure I had a look in the VS Code Github repo. Found this --> https://github.com/Microsoft/vscode/issues/8102 <-- however that leaves me/us with a need for a directive that can control if a specific extension is installed or not. Or alternatively we can go down the less intelligent road of just messaging the user via Plaster "message", to tell them that they should install the "Project snippets" extension in order for this to work.

What do you say? Thank you very much.

**Comment by rkeithhill** [comment]
You can add (or modify an existing) `.vscode\extensions.json` file that contains "recommended" extensions for the project.  But I would still probably add a message to indicate that they run the VSCode command `Extensions; Show Recommended Extensions`.

Whatever else we might do we would need to consider the case where the user just invokes the template from the console (or maybe even another editor).

**Comment by larssb** [comment]
@rkeithhill yeah found the documentation on it (here it is, for forthcoming peeping eyes: https://code.visualstudio.com/docs/editor/extension-gallery). Great idea. On the same VS Code documentation page I can also read that it is possible to execute the following cmdline: `code --list-extensions` <-- which makes me think that one could parse the output of that and confirm if "x" extension is installed or not. If it isn't then do `
code --install-extension "NAME OF EXTENSION TO INSTALL"`.....now, is that something that is within the scope of what Plaster tries to help us with?

Thank you.

**Comment by larssb** [comment]
@rkeithhill the suggestion I gave in the above, could that be a plausible solution?
