### ISSUE TITLE
Help with Parameter Condition

### ISSUE THREAD

**Issue by zacharyshupp** [PowerShellOrg/Plaster#276]
I have started looking into plaster. Reading through the documentation for parameters I see that we can use conditions which would be nice in my use case. Is there any examples posted on How to use condition? when I try and call it I get a schema error, below is the error i get.

```powershell
Plaster manifest schema error in file 'C:\Stencial\Stencials\Stencial-Module\plasterManifest.xml'. Error: The 'condition' attribute is not declared.
```

Below is what i was testing.

```xml
  <parameters>
    <parameter name='ProjectType' type='multichoice' default='0' prompt='Select Project Type'>
      <choice label='&amp;Personal' help='Create a new project for hosting on Personal Github' value='Personal'/>
      <choice label='&amp;Work' help='Create a new project for hosting on Work Source Control' value='Work'/>
    </parameter>
    <parameter name='GitHubUserName' condition="$PLASTER_PARAM_ProjectType='Personal'" type='text' prompt='Enter your GitHub user name' />
    <parameter name='VSTSUserName' condition="$PLASTER_PARAM_ProjectType='Work'" type='text' prompt='Enter your Visual Studio Team Services user name' />
  </parameters>
```

My goal was to make it so only one of the user name prompts would show up.

**Comment by rkeithhill** [comment]
In order to use the `condition` attribute on Plaster you have to build/run from the `master` branch since that particular feature hasn't been released yet.  Hopefully that will happen soon - maybe with the July release of the PowerShell extension for VSCode.  I have just one more feature I want to get in before releasing an update to Plaster. cc @daviwil

**Comment by zacharyshupp** [comment]
Thanks Keith for the info, I did pull master and I was able to get it working.

**Comment by gaelcolas** [comment]
Hi @rkeithhill, any update on the release date for this feature of Parameter with condition!
That'd be really useful!
/cc @daviwil
