### ISSUE TITLE
Consider changing template tests file to meet Pester v4 standard

### ISSUE THREAD

**Issue by PlagueHO** [PowerShellOrg/Plaster#295]
As of Pester v4.x the standard format for `Should` cmdlets should include `-` for each of the parameters. E.g.:
`Should Be $true` -> `Should -Be $true`
`Should BeNullOrEmpty` -> `Should -BeNullOrEmpty`

See [migration guide](https://github.com/pester/Pester/wiki/Migrating-from-Pester-3-to-Pester-4)

It might be a worth considering updating the default template to use this format.

There is also this migration script available to assist: https://gist.github.com/indented-automation/aeb14825e39dd8849beee44f681fbab3

**Comment by rkeithhill** [comment]
Thanks for the heads up.

**Comment by jdhitsolutions** [comment]
The module needs to be revised to support Pester 5.x.
