### ISSUE TITLE
XML Schema Document Not Found

### ISSUE THREAD

**Issue by DWSR** [PowerShellOrg/Plaster#298]
The XML Schema Document (http://www.microsoft.com/schemas/PowerShell/Plaster/v1) is resulting in an error page, causing the XML VSCode extension to format Plaster manifests poorly since it does not understand the document. Presumably, this is causing other errors as well.

**Comment by rkeithhill** [comment]
I don't think Microsoft actually makes schemas available at those URIs.  For instance, the MSBuild project schema `http://schemas.microsoft.com/developer/msbuild/2003` doesn't load in the browser.  Ditto for `http://schemas.microsoft.com/developer/vsx-schema/2010`.  The schema does ship with the Plaster module.  Is there a config file for XML extension where you can point it to the schema path?  The path is:
```
C:\Users\<username>\.vscode\extensions\ms-vscode.powershell-1.5.1\modules\Plaster\Schema\PlasterManifest-v1.xsd
```
Unfortunately, that path will change with each new rev of the extension.
