### ISSUE TITLE
Get-Plaster parameter enhancements

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShellOrg/Plaster#305]
I would very much like to see a -Title parameter for Get-Plaster to limit results as easily as using Get-Service. It would also be nice to have a -Tag parameter to also filter on one or more tags. Yes, I know I could do all of this myself with Where-Object, but getting a template by title name seems like such a common need it makes sense to include this filtering in the cmdlet.

**Comment by muzzar78** [comment]
Hey Jeff, I have been doing some work on Get-Plaster. The first change, which has been merged, exposes the template name in the object returned from Get-Plaster. The second change then allows you to filter on the name. This PR is open - https://github.com/PowerShell/Plaster/pull/323 if you want to add any comments.
