### ISSUE TITLE
Usage best practice

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShellOrg/Plaster#307]
The documentation isn't clear on this point so I thought I'd ask. Let's say I've built a Plaster template that I want to use on my computer. To make it easy to implement I think I have these options:

- Copy it to the Plaster module Template folder
- Create a Plaster module so I can use Get-PlasterTemplate -IncludeInstalledModules
- Create my own script or tooling to invoke the template

Is there a recommended best practice?

**Comment by rkeithhill** [comment]
If you are not publishing your template and you invoke Plaster manually, then you just specify the path to the template when you call Invoke-Plaster.  If you want VSCode to automatically find your template and offer to invoke it for you then it gets trickier.  @daviwil do you recall the exact way this is supposed to work?  IIRC you can create a PowerShell module with some stuff in the PrivateData section and that will cause Get-PlasterTemplate to find it. If Get-PlasterTemplate can find it, then VSCode can find & invoke it.

**Comment by jdhitsolutions** [comment]
By publishing, I assume you mean pushing something to the PSGallery. I stumbled across the VSCode task and my inference is that you need to create a plaster module with the private data tags.

**Comment by rkeithhill** [comment]
Yes, I mean publishing to the PSGallery.
