### ISSUE TITLE
Access Template from VSCode

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShellOrg/Plaster#309]
I created a Plaster module with the necessary extension data in the manifest. When I run `Get-PlasterTemplate -includeInstalledModules` I see the template. I can use it as expected from PowerShell.

In VSCode's command palette, I see the PowerShell option to create a new module from a Plaster template. Selecting it shows me the default templates included with the Plaster module. In the drop down there is an option to install additional templates from installed modules, but I can never get it to do anything or display additional templates.

Not sure if this is a VSCode or Plaster problem.

**Comment by jdhitsolutions** [comment]
Found the problem. I'm running Windows 10, but I also have PowerShell Core installed. The integrated PowerShell terminal in VSCode is using PSCore which by default doesn't see modules in C:\Program Files\WindowsPowerShell\Modules.  I use the Add-WindowsModulePath hack and now everything works as expected.

**Comment by rkeithhill** [comment]
Should we close this issue then?

**Comment by jdhitsolutions** [comment]
Probably. As PowerShell Core spreads this might be something to drop into documentation.

**Comment by rkeithhill** [comment]
OK, let's leave this open as a "documentation" issue.
