### ISSUE TITLE
Support adding required modules to the RequiredModules property in the module manifest.

### ISSUE THREAD

**Issue by larssb** [PowerShellOrg/Plaster#318]
Hi Plaster team,

Thank you for a great module. I was wondering if you are already considering to add support for; adding to the `RequiredModules` property in the module manifest? This would be great. Haven't been able to find anything about it in the docs or through a search in the issues section of this repository.
This would especially be nice if one is already using the `requireModule`directive in the Plaster manifest. As you are then prompting the user, but not adding the fact to the module. Which would be nice and transparent.

Thank you.

**Comment by X-Guardian** [comment]
Hi @larssb, since Pull request #315 was merged, you can now create a template psd1 module manifest file containing any required module manifest options that are not directly supported by Plaster, for example:

```
@{
# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    @{ModuleName = 'PowerShellGet'; ModuleVersion = '1.6.5'; }
    )
}
```
This can then be deployed as part of you PlasterManifest to the relevant destination, and then Plaster will update the module manifest with any other Plaster supported module manifest options that you have specified.

**Comment by larssb** [comment]
Nice...Thank you for this 👍

**Comment by oribesser** [comment]
Hey @X-Guardian , I couldn't make it work, maybe I'm missing something, appreciate your insight..
I have a Module.psd1 file in my template folder with only the relevant section as you described above, and I have a 'file' element that copies it to the generated module folder:
`<file source='Module.psd1' destination='${PLASTER_PARAM_ModuleName}.psd1'/>`
after this I have the 'newModuleManifest' element, but in the new generated module manifest the section from Module.psd1 is not included. I think that 'newModuleManifest' just overwrites the file.

**Comment by X-Guardian** [comment]
@oribesser, yes that should work. Are you using Plaster module v1.1.4 from this Git repository?

**Comment by oribesser** [comment]
uhmm… of course, now it works.. thanks
