### ISSUE TITLE
Add allowed command (Get-FileHash) in constrained runspace

### ISSUE THREAD

**Issue by hanpq** [PowerShellOrg/Plaster#325]
Please add Get-FileHash as an allowed cmdlet in the constrained runspace.

I write script modules for customers and include a pester test to verify the integrity of the included script files / folder structure etc. I would like to generate a filehash after Plaster has modified the files and then do another modify of the pester test scriptfile to include the newly generated hash.

Today I need to hardcode the filehashes in the pester test script. For scripts not modified by plaster I hardcode the filehashes in the pester test template and for scripts that plaster modify upon creation I always need to hardcode new hashes upon plaster creation.

I'm aware of script signing to verify code integrity however, for me hashes are sufficient as I just need this for troubleshooing purposes, I want to know that the scripts has not been altered. I'm also aware that this method is not stopping anyone from just calculating a new hash to put in the pester test for modified files so again it is not to address untrusting/malicious altering. 

This is my first submission of issue/feature request in github so I apologize in advance if there are any contribution rules that I've not fulfilled.

**Comment by hannespalmquist** [comment]
I cloned the repo and I think this might be the solution. Adding the following line in InvokePlaster.ps1 on line 273. (The function definition of get-filehash utilized foreach-object which is why the cmdlet foreach-object is also added.)

```
            $ssce = New-Object System.Management.Automation.Runspaces.SessionStateCmdletEntry 'Foreach-Object',([Microsoft.PowerShell.Commands.ForEachObjectCommand]),$null
            $iss.Commands.Add($ssce)

            $ssce = New-Object System.Management.Automation.Runspaces.SessionStateFunctionEntry 'Get-FileHash',(Get-Command -Name Get-FileHash).Definition
            $iss.Commands.Add($ssce)

```

**Comment by rkeithhill** [comment]
FYI that function is not available on PS 3 and not on PS Core either.  On PS Core, it has been converted to a cmdlet.

**Comment by rkeithhill** [comment]
Yeah, I already have that coded.  Just trying to determine if adding Foreach-Object opens up any holes in the constrained runspace.
