### ISSUE TITLE
Test-ModuleManifest fails in Core

### ISSUE THREAD

**Issue by Halkcyon** [PowerShellOrg/Plaster#353]
Related issue: https://github.com/PowerShell/PowerShell/issues/6818

When trying to import Plaster in PowerShell Core 6.2, the `Test-ModuleManifest` call in `Plaster.psm1` is failing, stating the manifest is invalid.  I am able to remediate this interactively doing

```powershell
Get-Module -ListAvailable -Refresh
Import-Module -Name Plaster -Force
```

but this remediation does not work when executed from my powershell profile.

Note: I could not replicate the behavior in Windows PowerShell 5.0.

***

My current workaround is modifying the `psm1` to:

```powershell
$PlasterVersion = [version](Import-PowerShellDataFile -Path $PSScriptRoot\Plaster.psd1)['ModuleVersion']
```

***

### Environment Details
* Windows 7 SP1 x64
* PowerShell Core 6.2

**Comment by jdhitsolutions** [comment]
Closing as a stale issue and that PowerShell Core is deprecated on desktop systems. We will be verifying that Plaster works properly in PowerShell 7.x
