### ISSUE TITLE
Is anyone maintaining this?

### ISSUE THREAD

**Issue by scott1138** [PowerShellOrg/Plaster#354]
I see there are some open merges and it doesn't look like the PowerShell Gallery has the latest version of the code.  Is this dead?

**Comment by rkeithhill** [comment]
The module is primarily distributed with the VSCode extension for PowerShell.  I can ping @TylerLeonhardt to see if we can publish an update to the PSGallery. But first I need to work through some of these PRs.

**Comment by jdhitsolutions** [comment]
Ownership has been transferred to PowerShell.org and work should be resuming.
