### ISSUE TITLE
Transfer of Ownership

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShellOrg/Plaster#362]
Microsoft has transferred ownership of this module to PowerShell.org.  It is our hope to bring this module back up to speed and maintain it for as long as the PowerShell community sees value in it. It will take us a little time to get things organized. It is very possible that many of the pull requests will be rejected so that we can start with a clean slate.

We are hoping to rely on the past expertise of the previous primary contributors:

+ @davegreen 
+ @devblackops 
+ @rkeithhill 
+ @TylerLeonhardt 

If your status with this project needs to change, send DM on Twitter (@JeffHicks)

**Comment by devblackops** [comment]
This is awesome to see! My [Stucco](https://github.com/devblackops/Stucco) project relies on Plaster, so I'm happy to see PowerShell.org taking over the project and ensuring it continues on.

**Comment by LaurentDardenne** [comment]
Does the project stay coupling to Visual Studio Code ?

**Comment by jdhitsolutions** [comment]
That's one of the things I have to look into. I'll need to check with @TylerLeonhardt to see what is happening now.

**Comment by TylerLeonhardt** [comment]
Yes I have no plans to remove the existing integration in the PowerShell extension and I personally am hoping that with Plaster getting some love, the integration can also get some love as well.

Id be happy to chat about how the integration works. It all should 'just work' still as long as the cmdlets don't change too much.

My ask is that new Plaster maintainers do test new versions of Plaster with the extension 🙂 so I don't get caught too off guard. 😅

**Comment by jeffpatton1971** [comment]
Have the schemas been moved from http://www.microsoft.com/schemas/PowerShell/Plaster/v1 ? Looking to leverage Plaster to enforce standards on my own modules as well as things I'm working on for my job. So am interested in that schema validation, and the idea that was presented a while back about customizing, or proposing metadata items.

**Comment by jdhitsolutions** [comment]
I honestly am not sure. That page at Microsoft doesn't exist. I'll have to check into what should happen now.

**Comment by jeffpatton1971** [comment]
Yea, I noticed that as well, which is why I asked. My understanding is that the XML was validated against that schema, if nobody knows it may be worth sorting out perhaps something based on JSON vs XML...just my two cents though ;-)

**Comment by jdhitsolutions** [comment]
I'm checking with Microsoft.

**Comment by rkeithhill** [comment]
Manifests are validated against the schema but if you have access to the schema file (it is in the repo `Release\Plaster\Schema\PlasterManifest-v1.xsd`) you don't need it to be served up over HTTP.  The other this is that `http://www.microsoft.com/schemas/PowerShell/Plaster/v1` is the schema's **namespace** so again, it doesn't have to exist at that URL.  It just ensures that the elements in a Plaster manifest have fully qualified names that include that namespace.

**Comment by jeffpatton1971** [comment]
@rkeithhill thanks for that clarification, would it make sense to transition that schema from XML to JSON?

**Comment by rkeithhill** [comment]
IMO no, not worth it. Whatever settings format you pick, someone is not going to like it. This is from the release notes on Windows Terminal:

> * Terminal will no longer complain if you leave trailing commas in your "JSON" settings (#6312)
    - What even is JSON anymore?
    - Yes, we perhaps chose a poor configuration format given that we expected users to have to hand-edit it.

**Comment by jeffpatton1971** [comment]
LOL fair...i guess XML being icky is not enough ;-) Most likely would be the same reasoning for making the schema a little more extensible

**Comment by sheppyh** [comment]
Is there anything I can do (as a random member of the public) to help get things re-organised? Triage of open issues?

**Comment by jonconley** [comment]
I'm with you @sheppyh. As we look at deploying some new modules, we've always used Plaster in the past. I'd love to continue down that path, but with the transfer in ownership and lack of activity, it is difficult to know where these project may be headed. If things are progressing, I'd love to contrib to this repo before creating or forking our own solution.

**Comment by davegreen** [comment]
As it's clear from the issues list, There's definitely a bunch to do, but I personally haven't had time to do anything with this project for a while.

In the main, it pretty much just works for my use cases, so it would be interesting to see where people want to extend the module.

@sheppyh You've hit the nail on the head about triaging issues and just dealing with what's here. I know one of the things I was going to look at is the publish task stuff to make it a bit better dealing with personal nuget repositories.

@jonconley I don't know about the other maintainers, but I'll try to put some time into looking at the existing pull requests. I'm not really particularly great at the internal of Plaster (I mostly contributed to the build scripts), but I'll do my best to put some time into it and see where we get to.

**Comment by tstager** [comment]
Any word on when any work will begin on 2.0?
