### ISSUE TITLE
Template Distribution.

### ISSUE THREAD

**Issue by gerane** [PowerShellOrg/Plaster#37]
I think it is worth starting a serious discussion on how these templates are going to be distributed and how Plaster could potentially detect installed templates. I have been seeing several people getting interested about Plaster, and the problem of distribution and just finding Plaster templates is becoming evident.
## PSGallery

I think the best distribution method would likely be the PSGallery and add a flag or something for plaster. However, I feel there is an issue with this that conflicts with the prevention of Code Execution in the Plaster Templates. If you install a module from the PSGallery, you just bypassed any attempt at preventing Code execution. If you are wanting to be malicious just have the code run at module installation and/or module import. The same goes with any other module, if you want to be malicious, just have it execute at module installation. 
## Template Detection

If Templates are distributed as modules, I think it would be beneficial for Plaster to be able to detect those templates in the module directories in some way. Maybe you have a standard folder name or other signal that Plaster can find. Instead of supplying a template path, I think it would be beneficial to either have a new command that prompts the user of template choices, or add a new method to invoke plaster that searches for installed templates and prompts the user.

I just wanted to get a dedicated discussion going on this and see what peoples thoughts were.

**Comment by daviwil** [comment]
@KirkMurno and I have been talking about this occasionally but haven't yet had a chance to start working on a solution for it.

Yeah, the Gallery is the best place to do distribution by default.  The idea we've been kicking around is to define a common folder structure for modules to include extensions that apply to other modules.  If we couple that with a special tag on the module in the Gallery then it should be pretty easy to find a list of modules on the user's machine that contain Plaster templates.  Once we locate those modules we should be able to check the module's installation path for the included templates and then present them to the user, no loading of the module needed.  A pure Plaster module shipped via the Gallery should only need a .psd1 and the correct folder structure.

Now that I read through your issue completely, it seems like you're saying the same thing :)

I think we'll definitely need a basic story for this for the first official release (which should theoretically should be happening in the next month or two).

**Comment by devblackops** [comment]
Any thoughts on also allowing the user to pull down a template from a Git repository? Obviously Git would need to be available on the system but I can see use cases where this would be useful.

Something like this would clone the repository into a temporary location, Plaster would use the template in the temp folder, generate the module, then remove the temp folder.

```powershell
Invoke-Plaster -GitUri 'https://github.com/devblackops/Module.Template.git' -Destination .\NewModule
```

**Comment by rkeithhill** [comment]
I don't think that Invoke-Plaster needs to support Git directly.  You can script this as:
```powershell
$tempPath = "${env:Temp}\$([guid]::NewGuid())"
New-Item $tempPath -ItemType Directory | Set-Location
git.exe clone https://github.com/devblackops/Module.Template.git
Invoke-Plaster -Template ./Module.Template -Destination $somePath
Remove-Item $tempPath -Recurse -Force
```

**Comment by daviwil** [comment]
Just filed an issue for implementing a `Get-PlasterTemplate` cmdlet which will use a template module resolution strategy that I'm currently designing: https://github.com/PowerShell/Plaster/issues/106

Working on a proposal for how we'll resolve template modules, will give more info on that in the next couple of days!

**Comment by rkeithhill** [comment]
Along the those lines, we probably should have a `New-PlasterManifest` command to help folks create the manifest file.  I'll add that one to my TODO list.

**Comment by daviwil** [comment]
Or have a Plaster template for creating Plaster templates :)

**Comment by rkeithhill** [comment]
My thinking was to mirror `New-ModuleManifest` kind of like we've done with `Test-ModuleManifest / Test-PlasterManifest`.  I want to be able to point to a directory of files and have the `New-PlasterManifest` auto-generate the `<file>` file directives in the manifest.  Since Plaster itself isn't quite full blow T4 type tool, this would be hard to do.

**Comment by daviwil** [comment]
That sounds good to me, it'd make things easier for a user who created a project and then wants to templatize it.

**Comment by rkeithhill** [comment]
I'm working on this command today.  Hopefully will have something ready to go in a few days.  Then need to start working on templates and integration with VSCode (unless we think we can rope in

**Comment by rkeithhill** [comment]
The `New-PlasterManifest` command has been implemented.
