### ISSUE TITLE
Add the possibility to create a parameter(variable) without require a keyboard input.

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShellOrg/Plaster#49]
I try to create a profile for my project. 
This file contain miscellaneous variables declaration, this variables are used inside a PSake script.
Today create a parameter/variable $Plaster requires a keyboard input.

``` powershell
<parameter name='ProjectName' type='input' store='text' prompt='Enter the project name'/>
<parameter name='Root' type='input' store='text' prompt='Enter the root of the project name'/>

  <!-- assert : the xml parsing is sequential -->
<Parameter name='ProjectRoot' type='NoInput' Value='${PLASTER_PARAM_Root}\${PLASTER_PARAM_ProjectName}'/>
<parameter name='Setup' type='NoInput' Value='${PLASTER_PARAM_ProjectRoot}\Setup'/>
...
<file source='Profile\Profile.T.ps1'
      destination='Profile\${PLASTER_PARAM_ProjectName}_profile.ps1'
      template='true'/>
```

With Profile\Profile.T.ps1 :

``` powershell
#Profile for the project <%=${PLASTER_PARAM_ProjectName}%>'
 param (
     [Parameter(Mandatory=$false)]
   [int]$Scope=1
 )#param

New-Variable -Name "<%=${PLASTER_PARAM_ProjectName}%>Setup" -Value '<%=${PLASTER_PARAM_Setup}%>'  -Option Constant -Scope $Scopee
...
```

**Comment by rkeithhill** [comment]
For this we would probably add a `<variables>` section after parameters as parameters are specifically for asking the template user for information.  But `<variables>` is unlikely to make it for the first release.  

You can easily work around this today with:
```powershell
New-Variable -Name "<%=${PLASTER_PARAM_ProjectName}%>Setup" -Value '<%=${PLASTER_PARAM_Root}\${PLASTER_PARAM_ProjectName}\Setup%>'  -Option Constant -Scope $Scope
```

BTW what do you expect the user to type in for `Root`?  If it is the same as the template's DestinationPath, you can already access that with $PLASTER_DestinationPath. If you need just the name of that dir, it is $PLASTER_DestinationName.  The invocation is supposed to guarantee that the template cannot write outside of the user specified DestinationPath.  That needs testing though.  :-)

P.S. Thanks for all the great feedback.  Keep it coming.

**Comment by LaurentDardenne** [comment]
_You can easily work around this today with:_
Yes, exactly. 

_If it is the same as the template's DestinationPath_
No, it is my working directory (G:\Dev\PS\ProjectName).

_Thanks for all the great feedback_
We  thank you for taking the time to build this tool.

**Comment by rkeithhill** [comment]
> No, it is my working directory (G:\Dev\PS\ProjectName).

You're just writing this into a file that lives under DestinationPath, right?  In theory, Plaster should not allow you to modify anything outside of DestinationPath except for a directive I'm thinking about adding - <InstallModule name="PSake"/> - which would write to the appropriate file system location.

**Comment by rkeithhill** [comment]
>  I am yet a bit confus about its use.

It's primary use, as I envision it, will be inside VSCode and ISE you will be able to invoke a command for a "New Module Project" this will invoke the corresponding Plaster template that will prompt the IDE user for information about the new module they want to create.  After they're done, the new module will be loaded by the IDE for the user.  

Of course, you will be able to use this from the CLI but I believe the primary use will be from IDEs.  This is similar to Visual Studio's `New Project Wizard`.

**Comment by LaurentDardenne** [comment]
Thank you Kheit, now I understand better his goal.
